import type { Metadata } from "next";
import { Montserrat, Figtree } from "next/font/google";
import "./globals.css";
import AuthInit from "@/providers/AuthInit";

const figtree = Figtree({
  variable: "--font-figtree",
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${figtree.className} antialiased`}
      >
        <AuthInit/>

          {children}
        

      </body>
    </html>
  );
}
